- name: Generate In-Memory Inventory of Image Builder VM
  hosts: localhost

- name: Configure Image Builder VM
  hosts: imagebuilder
  become: yes
  tasks:
#    - name: Register Host
#      community.general.redhat_subscription:
#        state: present
#        username: "{{ lookup('file', '/var/secrets/redhat-portal-credentials/username') }}"
#        password: "{{ lookup('file', '/var/secrets/redhat-portal-credentials/password') }}"
#        pool_ids: "{{ lookup('file', '/var/secrets/redhat-portal-credentials/pool_id') }}"
#      tags: repos

    - name: Setup Repositories
      community.general.rhsm_repository:
        state: enabled
        purge: yes
        name:
          - rhel-8-for-x86_64-appstream-rpms
          - rhel-8-for-x86_64-baseos-rpms
      tags: repos

    - name: Install Packages
      ansible.builtin.dnf:
        state: latest
        name:
          - osbuild-composer
          - composer-cli
          - cockpit-composer
          - bash-completion
          - firewalld
          - genisoimage
          - syslinux

    - name: Enable Cockpit/Composer/Firewalld
      ansible.builtin.systemd:
        state: started
        enabled: yes
        name: "{{ item }}"
      loop:
        - osbuild-composer
        - cockpit
        - firewalld

    - name: Enable Firewall Ports for Cockpit/Composer
      ansible.posix.firewalld:
        service: cockpit
        permanent: yes
        state: enabled
