- name: Create s3 bucket
  amazon.aws.aws_s3:
    bucket: "{{ bucket_name }}"
    mode: create

- name: Add image file to s3
  amazon.aws.aws_s3:
    bucket: "{{ bucket_name }}"
    object: "{{ build_uuid }}.raw"
    src: "{{ image_file_path }}"
    mode: put
  register: image_upload
  tags: upload_image

- name: List keys
  amazon.aws.aws_s3:
    bucket: "{{ bucket_name }}"
    mode: list

- name: Set image location
  set_fact:
    image_location_s3: "s3://{{ bucket_name }}/{{ build_uuid }}.raw"

- name: Create AMI
  amazon.aws.ec2_ami:
    region: "{{ aws_region }}"
    wait: yes
    name: "{{ bucket_name }}-{{ build_uuid }}"
    image_location: "{{ image_location_s3 }}"
    device_mapping:
      - device_name: /dev/sda1
        size: 6
        delete_on_termination: true
        volume_type: gp2
