- name: Create s3 bucket
  amazon.aws.aws_s3:
    bucket: "{{ bucket_name }}"
    mode: create

- name: Add image file to s3
  amazon.aws.aws_s3:
    bucket: "{{ bucket_name }}"
    object: "{{ build_uuid }}.raw"
    src: "{{ image_file_path }}"
    mode: put
  register: image_upload

- name: Debug image_upload
  ansible.builtin.debug:
    msg: "{{ image_upload }}"

- name: List keys
  amazon.aws.aws_s3:
    bucket: "{{ bucket_name }}"
    mode: list

- name: Set image location
  set_fact:
    image_location_s3: "https://{{ bucket_name }}.s3.amazonaws.com/{{ build_uuid }}.raw"

- name: Create AMI
  amazon.aws.ec2_ami:
    image_location: "{{ image_location_s3 }}"
    wait: yes
    name: "{{ bucket_name }}-{{ build_uuid }}"
